[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend && npm install --prefix backend"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "backend/functions"
  node_bundler = "esbuild"
  included_files = ["backend/**"]
  external_node_modules = [
    "express",
    "cors",
    "dotenv",
    "serverless-http",
    "bcrypt",
    "@supabase/supabase-js",
    "jsonwebtoken",
    "@google/generative-ai",
    "ollama"
  ]

[functions.api]
  timeout = 26

[dev]
  command = "npm start --prefix frontend"
  targetPort = 3000
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
