import React from 'react';
import { Link } from 'react-router-dom';
import Carousel from '../components/Carousel';
import NewsReel from '../components/NewsReel';

const Landing = () => {
  const features = [
    {
      title: 'AI Roadmaps',
      desc: 'Get a personalized 5-year academic and career roadmap generated by our advanced RAG-based AI.',
      icon: '✨',
      color: 'blue',
    },
    {
      title: 'Global Database',
      desc: 'Explore 5000+ programs across 50+ countries with real-time budget and requirement filters.',
      icon: '🌍',
      color: 'green',
    },
    {
      title: 'Expert Support',
      desc: 'Connect with verified alumni and consultants to guide your application process.',
      icon: '🛡️',
      color: 'purple',
    },
    {
      title: 'Scholarship Tracker',
      desc: 'Monitor latest scholarships and financial aid opportunities tailored to your profile.',
      icon: '💰',
      color: 'orange',
    },
  ];

  return (
    <div className="space-y-16 pb-20 -mt-8">
      {/* Top News Reel */}
      <div className="-mx-4 md:-mx-8 lg:-mx-8">
        <NewsReel />
      </div>

      {/* Hero Carousel */}
      <section className="px-0">
        <Carousel />
      </section>

      {/* Stats Section */}
      <section className="grid grid-cols-2 md:grid-cols-4 gap-8 py-10 bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-700 transition-colors duration-300">
        {[
          { label: 'Universities', value: '500+' },
          { label: 'Scholarships', value: '$10M+' },
          { label: 'Success Rate', value: '94%' },
          { label: 'Countries', value: '50+' },
        ].map((stat, i) => (
          <div key={i} className="text-center">
            <div className="text-3xl font-bold text-blue-600 dark:text-blue-400">{stat.value}</div>
            <div className="text-sm font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">{stat.label}</div>
          </div>
        ))}
      </section>

      {/* Features Grid */}
      <section>
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-800 dark:text-gray-100 mb-4">
            Everything you need for your <span className="text-blue-600 dark:text-blue-400 text-underline">Global Journey</span>
          </h2>
          <p className="text-gray-500 dark:text-gray-400 max-w-2xl mx-auto">
            StudyGlobe combines big data with personalized AI to simplify every step of your international education.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((f, i) => (
            <div key={i} className="bg-white dark:bg-gray-800 p-8 rounded-2xl shadow-sm hover:shadow-xl transition-all border border-gray-100 dark:border-gray-700 group">
              <div className="text-4xl mb-4 group-hover:scale-110 transition-transform duration-300">{f.icon}</div>
              <h3 className="text-xl font-bold text-gray-800 dark:text-gray-100 mb-2">{f.title}</h3>
              <p className="text-gray-500 dark:text-gray-400 text-sm leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-blue-700 dark:bg-blue-900 rounded-3xl p-8 md:p-16 text-center text-white relative overflow-hidden shadow-2xl transition-colors duration-300">
        <div className="relative z-10">
          <h2 className="text-3xl md:text-5xl font-bold mb-6">Ready to change your life?</h2>
          <p className="text-blue-100 text-lg mb-10 max-w-xl mx-auto">
            Join 10,000+ students who started their journey with StudyGlobe. The world is waiting for you.
          </p>
          <Link
            to="/register"
            className="bg-white text-blue-700 hover:bg-blue-50 font-bold py-4 px-10 rounded-2xl transition-all hover:scale-105 shadow-xl inline-block"
          >
            Create Your Account
          </Link>
        </div>
        
        {/* Animated Orbs */}
        <div className="absolute top-0 right-0 -translate-y-1/2 translate-x-1/2 w-64 h-64 bg-blue-500 rounded-full blur-[100px] opacity-50" />
        <div className="absolute bottom-0 left-0 translate-y-1/2 -translate-x-1/2 w-64 h-64 bg-indigo-500 rounded-full blur-[100px] opacity-50" />
      </section>
    </div>
  );
};

export default Landing;
